### ISSUE TITLE
pth 转换到pt

### ISSUE THREAD

**Issue by 471448446** [COO1M/SRMaster#1]
观察到pytorch mobile 使用的是`.pt`文件的模型格式。

请问，模型转换的地方是如何操作的呢？

我使用的代码如下：

```pthon
import torch
import torch.utils.data.distributed

# pytorch环境中
model_pth = 'realesr-general-x4v3.pth'  # 模型的参数文件
mobile_pt = 'realesr-general-x4v3.pt'  # 将模型保存为Android可以调用的文件

model = torch.load(model_pth, map_location=torch.device('cpu'))
model.eval()  # 模型设为评估模式
device = torch.device('cpu')
model.to(device)
# 1张3通道224*224的图片
input_tensor = torch.rand(1, 3, 224, 224)  # 设定输入数据格式

mobile = torch.jit.trace(model, input_tensor)  # 模型转化
mobile.save(mobile_pt)  # 保存文件
```
但是始终报错：AttributeError: 'dict' object has no attribute 'eval'

**Comment by COO1M** [comment]
要用realesrgan的模型结构，可以查看一下realesrgan的相关代码，例如 [inference_realesrgan.py](https://github.com/xinntao/Real-ESRGAN/blob/master/inference_realesrgan.py) 和 [pytorch2onnx.py](https://github.com/xinntao/Real-ESRGAN/blob/master/scripts/pytorch2onnx.py)

**Comment by 471448446** [comment]
> 要用realesrgan的模型结构，可以查看一下realesrgan的相关代码，例如 [inference_realesrgan.py](https://github.com/xinntao/Real-ESRGAN/blob/master/inference_realesrgan.py) 和 [pytorch2onnx.py](https://github.com/xinntao/Real-ESRGAN/blob/master/scripts/pytorch2onnx.py)

感谢，已解决
