### ISSUE TITLE
大佬，有联系方式没？

### ISSUE THREAD

**Issue by einsqing** [COO1M/SRMaster#3]
大佬，有联系方式没？

**Comment by COO1M** [comment]
不是大佬，这个app写得很简单。有什么要交流的吗？

**Comment by einsqing** [comment]
> 不是大佬，这个app写得很简单。有什么要交流的吗？

我看咱这个网络层非常简单，速度非常快，请问real-esrgan训练出来的如何精简一下？或者加速推理的还有什么方案么？我测试咱自带的模型，速度非常快200ms就出来了，我训练的模型real-esrgan转onnx fp16的，要1500ms

**Comment by COO1M** [comment]
> > 不是大佬，这个app写得很简单。有什么要交流的吗？
> 
> 我看咱这个网络层非常简单，速度非常快，请问real-esrgan训练出来的如何精简一下？或者加速推理的还有什么方案么？我测试咱自带的模型，速度非常快200ms就出来了，我训练的模型real-esrgan转onnx fp16的，要1500ms

实际上，正如readme里所写，这个demo中主要的工作是将官方的模型文件转换到各格式的移动端模型进行部署，侧重于移动端模型转换和部署方面，因此你的问题可能需要查询官方文档或向官方社区寻求帮助，我仅按照这些地方进行处理模型。

**Comment by einsqing** [comment]
> > > 不是大佬，这个app写得很简单。有什么要交流的吗？
> > 
> > 
> > 我看咱这个网络层非常简单，速度非常快，请问real-esrgan训练出来的如何精简一下？或者加速推理的还有什么方案么？我测试咱自带的模型，速度非常快200ms就出来了，我训练的模型real-esrgan转onnx fp16的，要1500ms
> 
> 实际上，正如readme里所写，这个demo中主要的工作是将官方的模型文件转换到各格式的移动端模型进行部署，侧重于移动端模型转换和部署方面，因此你的问题可能需要查询官方文档或向官方社区寻求帮助，我仅按照这些地方进行处理模型。

您转换的是官方哪个模型？使用https://github.com/xinntao/Real-ESRGAN/blob/master/scripts/pytorch2onnx.py 转换的么？我转换之后比您的这个模型大的多，而且结构也复杂的多，能加您微信么？可以付费

**Comment by COO1M** [comment]
> > > > 不是大佬，这个app写得很简单。有什么要交流的吗？
> > > 
> > > 
> > > 我看咱这个网络层非常简单，速度非常快，请问real-esrgan训练出来的如何精简一下？或者加速推理的还有什么方案么？我测试咱自带的模型，速度非常快200ms就出来了，我训练的模型real-esrgan转onnx fp16的，要1500ms
> > 
> > 
> > 实际上，正如readme里所写，这个demo中主要的工作是将官方的模型文件转换到各格式的移动端模型进行部署，侧重于移动端模型转换和部署方面，因此你的问题可能需要查询官方文档或向官方社区寻求帮助，我仅按照这些地方进行处理模型。
> 
> 您转换的是官方哪个模型？使用https://github.com/xinntao/Real-ESRGAN/blob/master/scripts/pytorch2onnx.py 转换的么？我转换之后比您的这个模型大的多，而且结构也复杂的多，能加您微信么？可以付费

V3模型，在[V2.5 Release](https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.5.0)里，或许是你没拿这个模型。转换的话，我不太记得起来是否仅做的你这个脚本里的工作，pytorch、onnx官网的文档、文章都可以看看，还有其github issue搜搜关键词，也有许多资料。

**Comment by einsqing** [comment]
> > > > > 不是大佬，这个app写得很简单。有什么要交流的吗？
> > > > 
> > > > 
> > > > 我看咱这个网络层非常简单，速度非常快，请问real-esrgan训练出来的如何精简一下？或者加速推理的还有什么方案么？我测试咱自带的模型，速度非常快200ms就出来了，我训练的模型real-esrgan转onnx fp16的，要1500ms
> > > 
> > > 
> > > 实际上，正如readme里所写，这个demo中主要的工作是将官方的模型文件转换到各格式的移动端模型进行部署，侧重于移动端模型转换和部署方面，因此你的问题可能需要查询官方文档或向官方社区寻求帮助，我仅按照这些地方进行处理模型。
> > 
> > 
> > 您转换的是官方哪个模型？使用https://github.com/xinntao/Real-ESRGAN/blob/master/scripts/pytorch2onnx.py 转换的么？我转换之后比您的这个模型大的多，而且结构也复杂的多，能加您微信么？可以付费
> 
> V3模型，在[V2.5 Release](https://github.com/xinntao/Real-ESRGAN/releases/tag/v0.2.5.0)里，或许是你没拿这个模型。转换的话，我不太记得起来是否仅做的你这个脚本里的工作，pytorch、onnx官网的文档、文章都可以看看，还有其github issue搜搜关键词，也有许多资料。

我使用的RRDBNet，模型大小32m，onnx速度1.5s，pytorch mobile 2.5s，大佬有什么建议么？将速度提升到0.03s。模型是基于[RealESRGAN_x4plus.pth](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth)训练的

**Comment by COO1M** [comment]
那就只有试试看新的SRVGGNetCompact，否则无非就是量化那些杂七杂八的常规手段，可能你已经有使用过了
